package LoginAndRegister.view;


import LoginAndRegister.entity.Books;
import LoginAndRegister.connection.MyConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bertomalone
 */
public class ADMIN_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN_JFrame
     */
    public ADMIN_JFrame() {
        initComponents();
        Show_Book_On_JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public boolean checkInputs()
    {
        if(
              jTextField_idBuku.getText() == null
           || jTextField_judulBuku.getText() == null
           || jTextField_penulisBuku.getText()== null
           || jDateChooser_tglMasukBuku.getDate() == null
           
          ){
            return false;
        }
        else{
            try{
                Integer.parseInt(jTextField_hargaBuku.getText());
                Integer.parseInt(jTextField_thnTerbitBuku.getText());
                Integer.parseInt(jTextField_stokBuku.getText());
                return true;
            }catch(Exception ex)
            {
                return false;
            }
        }
    }
    
    public ArrayList<Books> getBooksList() {
        ArrayList<Books> booksList  = new ArrayList<Books>();
        Connection stmt = MyConnection.getConnection();
        String query = "SELECT * FROM tbl_daftar_buku";
        
        Statement st;
        ResultSet rs;
        
        try {
            st = stmt.createStatement();
            rs = st.executeQuery(query);
            
            Books book;
            
            while(rs.next()) {
                book = new Books(rs.getString("id_buku"), rs.getString("judul_buku"), rs.getString("penulis_buku"), rs.getString("tanggal_masuk"), rs.getInt("harga_buku"), rs.getInt("tahun_terbit"), rs.getInt("stok_buku"));
                booksList.add(book);
            }
            
        } catch(SQLException ex) {
            Logger.getLogger(ADMIN_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return booksList;
    }
    
    public void Show_Book_On_JTable() {
        ArrayList<Books> list = getBooksList();
        DefaultTableModel model = (DefaultTableModel)jTable_tabelBuku.getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[7];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getJudul();
            row[2] = list.get(i).getPenulis();
            row[3] = list.get(i).getTanggalMasuk();
            row[4] = list.get(i).getHarga();
            row[5] = list.get(i).getTahunTerbit();
            row[6] = list.get(i).getStok();
            
            model.addRow(row);
        }
 
    }
    
    public void ShowBook(int index) {
//        txt_id.setText(Integer.toString(getProductList().get(index).getId()));
//            txt_name.setText(getProductList().get(index).getName());
//            txSQLExceptiont_price.setText(Float.toString(getProductList().get(index).getPrice()));

        jTextField_idBuku.setText(getBooksList().get(index).getId());
        jTextField_judulBuku.setText(getBooksList().get(index).getJudul());
        jTextField_penulisBuku.setText(getBooksList().get(index).getPenulis());
                    
        try {
            Date addDate = null;
            addDate = new SimpleDateFormat("yyyy-MM-dd").parse((String)getBooksList().get(index).getTanggalMasuk());
            jDateChooser_tglMasukBuku.setDate(addDate);
        } catch (ParseException ex) {
            Logger.getLogger(ADMIN_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextField_hargaBuku.setText(Integer.toString(getBooksList().get(index).getHarga()));
        jTextField_thnTerbitBuku.setText(Integer.toString(getBooksList().get(index).getTahunTerbit()));
        jTextField_stokBuku.setText(Integer.toString(getBooksList().get(index).getStok()));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_admin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_idBuku = new javax.swing.JTextField();
        jTextField_judulBuku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_penulisBuku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_hargaBuku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_thnTerbitBuku = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_stokBuku = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser_tglMasukBuku = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabelBuku = new javax.swing.JTable();
        jButton_insert_ = new javax.swing.JButton();
        jButton_update_ = new javax.swing.JButton();
        jButton_delete_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 196, 14));

        jLabel_admin.setFont(new java.awt.Font("Noto Sans", 0, 23)); // NOI18N
        jLabel_admin.setForeground(java.awt.Color.white);
        jLabel_admin.setText("Admin");

        jLabelClose.setBackground(new java.awt.Color(240, 196, 14));
        jLabelClose.setFont(new java.awt.Font("Noto Sans", 0, 32)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(245, 235, 235));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setIcon(new javax.swing.ImageIcon("/home/bertomalone/Downloads/icon.png")); // NOI18N
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMinimize.setBackground(new java.awt.Color(240, 196, 14));
        jLabelMinimize.setFont(new java.awt.Font("Noto Sans", 0, 32)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(245, 235, 235));
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setIcon(new javax.swing.ImageIcon("/home/bertomalone/Downloads/minimize (1).png")); // NOI18N
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel_admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMinimize)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(27, 188, 155));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("ID Buku :");

        jTextField_idBuku.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_idBuku.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTextField_idBuku.setForeground(new java.awt.Color(228, 241, 254));

        jTextField_judulBuku.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_judulBuku.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTextField_judulBuku.setForeground(new java.awt.Color(228, 241, 254));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Judul :");

        jTextField_penulisBuku.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_penulisBuku.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTextField_penulisBuku.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_penulisBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_penulisBukuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Penulis :");

        jTextField_hargaBuku.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_hargaBuku.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTextField_hargaBuku.setForeground(new java.awt.Color(228, 241, 254));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Harga :");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Tahun Terbit :");

        jTextField_thnTerbitBuku.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_thnTerbitBuku.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTextField_thnTerbitBuku.setForeground(new java.awt.Color(228, 241, 254));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Stok Buku :");

        jTextField_stokBuku.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_stokBuku.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTextField_stokBuku.setForeground(new java.awt.Color(228, 241, 254));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Tanggal Masuk :");

        jDateChooser_tglMasukBuku.setBackground(new java.awt.Color(108, 122, 137));

        jTable_tabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Buku", "Judul", "Penulis", "Tanggal Masuk", "Harga", "Tahun Terbit", "Stok Buku"
            }
        ));
        jTable_tabelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tabelBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_tabelBuku);

        jButton_insert_.setBackground(new java.awt.Color(67, 176, 92));
        jButton_insert_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_insert_.setForeground(java.awt.Color.white);
        jButton_insert_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/plus.png"))); // NOI18N
        jButton_insert_.setText("Insert");
        jButton_insert_.setIconTextGap(15);
        jButton_insert_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insert_ActionPerformed(evt);
            }
        });

        jButton_update_.setBackground(new java.awt.Color(50, 190, 166));
        jButton_update_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_update_.setForeground(java.awt.Color.white);
        jButton_update_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/refresh.png"))); // NOI18N
        jButton_update_.setText("Update");
        jButton_update_.setIconTextGap(15);
        jButton_update_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_update_ActionPerformed(evt);
            }
        });

        jButton_delete_.setBackground(new java.awt.Color(226, 27, 27));
        jButton_delete_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_delete_.setForeground(java.awt.Color.white);
        jButton_delete_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/delete.png"))); // NOI18N
        jButton_delete_.setText("Delete");
        jButton_delete_.setIconTextGap(15);
        jButton_delete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_idBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_penulisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(161, 161, 161)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_update_, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_insert_)
                            .addComponent(jButton_delete_)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_thnTerbitBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_stokBuku, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)))
                        .addGap(622, 622, 622))
                    .addComponent(jTextField_hargaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_tglMasukBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_idBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(jTextField_judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton_update_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_insert_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton_delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jTextField_penulisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser_tglMasukBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_hargaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_thnTerbitBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_stokBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jButton_insert_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insert_ActionPerformed
        if(checkInputs()) {
            try {
                PreparedStatement stmt = MyConnection.getConnection().prepareStatement("INSERT INTO `tbl_daftar_buku`(`id_buku`, `judul_buku`, `penulis_buku`, `tanggal_masuk`, `harga_buku`, `tahun_terbit`, `stok_buku`) "
                        + "VALUES (?,?,?,?,?,?,?)");

                stmt.setString(1, jTextField_idBuku.getText());
                stmt.setString(2, jTextField_judulBuku.getText());
                stmt.setString(3, jTextField_penulisBuku.getText());

                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String addDate = dateFormat.format(jDateChooser_tglMasukBuku.getDate());
                stmt.setString(4, addDate);

                stmt.setString(5, jTextField_hargaBuku.getText());
                stmt.setString(6, jTextField_thnTerbitBuku.getText());
                stmt.setString(7, jTextField_stokBuku.getText());

                stmt.executeUpdate();

                Show_Book_On_JTable();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "One Or More Field Are Empty");
        }
    }//GEN-LAST:event_jButton_insert_ActionPerformed

    private void jButton_update_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_update_ActionPerformed

        if(checkInputs() && jTextField_idBuku.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection con = MyConnection.getConnection();
            
            try {
                UpdateQuery = "UPDATE tbl_daftar_buku SET judul_buku = ?, penulis_buku = ?, tanggal_masuk = ?"
                + ", harga_buku = ?, tahun_terbit = ?, stok_buku = ? WHERE id_buku = ?";
                ps = con.prepareStatement(UpdateQuery);

                ps.setString(1, jTextField_judulBuku.getText());
                ps.setString(2, jTextField_penulisBuku.getText());

                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String addDate = dateFormat.format(jDateChooser_tglMasukBuku.getDate());
                ps.setString(3, addDate);

                ps.setInt(4, Integer.parseInt(jTextField_hargaBuku.getText()));
                ps.setInt(5, Integer.parseInt(jTextField_thnTerbitBuku.getText()));
                ps.setInt(6, Integer.parseInt(jTextField_stokBuku.getText()));
                ps.setString(7, jTextField_idBuku.getText());

                ps.executeUpdate();
                Show_Book_On_JTable();
                JOptionPane.showMessageDialog(null, "Product Updated");

            } catch (SQLException ex) {
                Logger.getLogger(ADMIN_JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }else{
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty Or Wrong");
        }
    }//GEN-LAST:event_jButton_update_ActionPerformed

    private void jButton_delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete_ActionPerformed

        if(!jTextField_idBuku.getText().equals(""))
        {
            try {
                Connection con = MyConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("DELETE FROM tbl_daftar_buku WHERE id_buku = ?");
                String id = jTextField_idBuku.getText();
                ps.setString(1, id);
                ps.executeUpdate();
                Show_Book_On_JTable();
                JOptionPane.showMessageDialog(null, "Product Deleted");
            } catch (SQLException ex) {
                Logger.getLogger(ADMIN_JFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Product Not Deleted");
            }

        }else{
            JOptionPane.showMessageDialog(null, "Product Not Deleted : No Id To Delete");
        }

    }//GEN-LAST:event_jButton_delete_ActionPerformed

    private void jTextField_penulisBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_penulisBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_penulisBukuActionPerformed

    private void jTable_tabelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tabelBukuMouseClicked
        // TODO add your handling code here:
        int index = jTable_tabelBuku.getSelectedRow();
        ShowBook(index);
    }//GEN-LAST:event_jTable_tabelBukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_delete_;
    private javax.swing.JButton jButton_insert_;
    private javax.swing.JButton jButton_update_;
    private com.toedter.calendar.JDateChooser jDateChooser_tglMasukBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinimize;
    public javax.swing.JLabel jLabel_admin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_tabelBuku;
    private javax.swing.JTextField jTextField_hargaBuku;
    private javax.swing.JTextField jTextField_idBuku;
    private javax.swing.JTextField jTextField_judulBuku;
    private javax.swing.JTextField jTextField_penulisBuku;
    private javax.swing.JTextField jTextField_stokBuku;
    private javax.swing.JTextField jTextField_thnTerbitBuku;
    // End of variables declaration//GEN-END:variables
}
