package LoginAndRegister.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import LoginAndRegister.entity.Books;
import LoginAndRegister.entity.Users;
import LoginAndRegister.entity.Penjualan;
import LoginAndRegister.implement.ImplemBooks;
import LoginAndRegister.implement.ImplemUsers;
import LoginAndRegister.implement.ImplemPenjualan;
import LoginAndRegister.interfaces.InterBooks;
import LoginAndRegister.interfaces.InterUsers;
import LoginAndRegister.interfaces.InterPenjualan;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bertomalone
 */
public class HOME_JFrame extends javax.swing.JFrame {
    private List<Penjualan> reqPenjualan = new ArrayList<>();
    private List<Books> reqBuku = new ArrayList<>();
    InterBooks daoBooks;
    InterPenjualan daoPenjualan;
    InterUsers daoUsers;
    Users role;

    /**
     * Creates new form HOME_JFrame
     */
    public HOME_JFrame(String user) {
        try {
            initComponents();
            daoBooks = new ImplemBooks();
            daoUsers = new ImplemUsers();
            role = daoUsers.getByUsername(user);
        } catch(SQLException ex) {
            Logger.getLogger(HOME_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }  
        this.statusAwal();
    }

    
    
    void isiTabelPenjualan() {
        Object data[][] = new Object[reqPenjualan.size()][4];
        int x = 0;
        for (Penjualan p : reqPenjualan) {
            data[x][0] = p.getBuku().getId();
            data[x][1] = p.getBuku().getJudul();
            data[x][2] = p.getJumlah();
            data[x][3] = p.getTotal();
            x++;
        }
        String judul[] = {"ID", "Judul", "Jumlah", "Harga"};
        jTable_Pembelian.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(jTable_Pembelian);
    }
    
    void kosongkanTabelPenjualan() {
        jTable_Pembelian.setModel(new DefaultTableModel(new Object[][]{{"", "", "", "",}}, new String[]{"ID", "Judul", "Jumlah", "Harga"}));
    }
    
    void KosongkanTabelCari() {
        jTable_Cari.setModel(new DefaultTableModel(new Object[][]{{"", "", ""}}, new String[]{"ID", "Judul", "Harga"}));
    }
    
    void isiTabelCari() {
        Object data[][] = new Object[reqBuku.size()][3];
        int x = 0;
        for (Books k : reqBuku) {
            data[x][0] = k.getId();
            data[x][1] = k.getJudul();
            data[x][2] = k.getHarga();
            x++;
        }
        String judul[] = {"ID", "Judul", "Harga"};
        jTable_Cari.setModel(new DefaultTableModel(data, judul));
        jScrollPane2.setViewportView(jTable_Cari);
    }
    
    double totalHarga() {
        double t = 0;
        for (Penjualan p : reqPenjualan) {
            t += p.getTotal();
        }
        return t;
    }
    
    void statusAwal() {
        this.kosongkanTabelPenjualan();
        this.KosongkanTabelCari();
        jTextField_Total.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_textCari = new javax.swing.JTextField();
        jButton_buttonCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Cari = new javax.swing.JTable();
        jButton_buttonMasukan_ = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_textId = new javax.swing.JTextField();
        jTextField_textJumlah = new javax.swing.JTextField();
        jButton_buttonLihat = new javax.swing.JButton();
        jButton_buttonAmbil_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Pembelian = new javax.swing.JTable();
        jButton_buttonHapus = new javax.swing.JButton();
        jTextField_Total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_buttonProses_ = new javax.swing.JButton();
        jFormattedTextField_tanggal = new javax.swing.JFormattedTextField();

        jPanel3.setBackground(new java.awt.Color(27, 188, 155));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("ID Buku :");

        jTextField_textCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_textCariKeyPressed(evt);
            }
        });

        jButton_buttonCari.setText("Cari");
        jButton_buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buttonCariActionPerformed(evt);
            }
        });

        jTable_Cari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(jTable_Cari);

        jButton_buttonMasukan_.setText("Masukkan");
        jButton_buttonMasukan_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buttonMasukan_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_textCari, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_buttonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton_buttonMasukan_, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_textCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buttonCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton_buttonMasukan_)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 196, 14));
        jPanel1.setPreferredSize(new java.awt.Dimension(588, 95));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 23)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Kasir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(27, 188, 155));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Id Buku :");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Jumlah :");

        jTextField_textId.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_textIdActionPerformed(evt);
            }
        });

        jTextField_textJumlah.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_textJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_textJumlahActionPerformed(evt);
            }
        });

        jButton_buttonLihat.setText("Lihat");
        jButton_buttonLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buttonLihatActionPerformed(evt);
            }
        });

        jButton_buttonAmbil_.setText("Ambil");
        jButton_buttonAmbil_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buttonAmbil_ActionPerformed(evt);
            }
        });

        jTable_Pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Pembelian);

        jButton_buttonHapus.setText("Hapus");
        jButton_buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buttonHapusActionPerformed(evt);
            }
        });

        jTextField_Total.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TotalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Total :");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Tanggal :");

        jButton_buttonProses_.setText("Proses");
        jButton_buttonProses_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buttonProses_ActionPerformed(evt);
            }
        });

        jFormattedTextField_tanggal.setEditable(false);

        jFormattedTextField_tanggal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MMMM yyyy"))));

        jFormattedTextField_tanggal.setValue(new java.util.Date());
        jFormattedTextField_tanggal.setBackground(new java.awt.Color(108, 122, 137));
        jFormattedTextField_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_tanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_buttonProses_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_textId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_buttonLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_buttonAmbil_, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buttonLihat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buttonAmbil_))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_buttonHapus)
                    .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton_buttonProses_)
                    .addComponent(jFormattedTextField_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_textIdActionPerformed

    private void jTextField_textJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_textJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_textJumlahActionPerformed

    private void jTextField_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TotalActionPerformed

    private void jButton_buttonLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buttonLihatActionPerformed
        // TODO add your handling code here:
        jDialog1.setSize(440, 350);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton_buttonLihatActionPerformed

    private void jButton_buttonAmbil_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buttonAmbil_ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Penjualan p = new Penjualan();
            Books b = daoBooks.getByOne(jTextField_textId.getText());
            double total = Double.parseDouble(jTextField_textJumlah.getText()) * b.getHarga();
            p.setBuku(b);
            p.setJumlah(Integer.parseInt(jTextField_textJumlah.getText()));
            p.setTanggal((Date) jFormattedTextField_tanggal.getValue());
            p.setTotal(total);
            p.setUsers(role);
            reqPenjualan.add(p);
        } catch (SQLException ex) {
            Logger.getLogger(HOME_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.isiTabelPenjualan();
        jTextField_Total.setText(String.valueOf(totalHarga()));
        jTextField_textId.setText("");
        jTextField_textJumlah.setText("");
        jTextField_textId.requestFocus();
    }//GEN-LAST:event_jButton_buttonAmbil_ActionPerformed

    private void jButton_buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buttonHapusActionPerformed
        // TODO add your handling code here:
        reqPenjualan.remove(jTable_Pembelian.getSelectedRow());
        this.isiTabelPenjualan();
    }//GEN-LAST:event_jButton_buttonHapusActionPerformed

    private void jTextField_textCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_textCariKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            reqBuku = daoBooks.getById(jTextField_textCari.getText());
            this.isiTabelCari();
        } catch (SQLException ex) {
            Logger.getLogger(HOME_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_textCariKeyPressed

    private void jButton_buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buttonCariActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            reqBuku = daoBooks.getById(jTextField_textCari.getText());
            this.isiTabelCari();
        } catch (SQLException ex) {
            Logger.getLogger(HOME_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_buttonCariActionPerformed

    private void jButton_buttonMasukan_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buttonMasukan_ActionPerformed
        // TODO add your handling code here:
        Books b = reqBuku.get(jTable_Cari.getSelectedRow());
        jTextField_textId.setText(b.getId());
        jTextField_textJumlah.requestFocus();
        jTextField_textCari.setText("");
        reqBuku.clear();
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton_buttonMasukan_ActionPerformed

    private void jButton_buttonProses_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buttonProses_ActionPerformed
        // TODO add your handling code here:
        if(!reqPenjualan.isEmpty()){
            reqPenjualan.forEach((p) -> {
                try {
                    daoPenjualan.insert(p);
                } catch (SQLException ex) {
                    Logger.getLogger(HOME_JFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            });
        reqPenjualan.clear();
        JOptionPane.showMessageDialog(this, "Pembelian Berhasil Total harga " +jTextField_Total.getText(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
        this.statusAwal();
        }else{
            JOptionPane.showMessageDialog(this, "Tidak ada transaksi pembelian", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_buttonProses_ActionPerformed

    private void jFormattedTextField_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_tanggalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buttonAmbil_;
    private javax.swing.JButton jButton_buttonCari;
    private javax.swing.JButton jButton_buttonHapus;
    private javax.swing.JButton jButton_buttonLihat;
    private javax.swing.JButton jButton_buttonMasukan_;
    private javax.swing.JButton jButton_buttonProses_;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFormattedTextField_tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Cari;
    private javax.swing.JTable jTable_Pembelian;
    private javax.swing.JTextField jTextField_Total;
    private javax.swing.JTextField jTextField_textCari;
    private javax.swing.JTextField jTextField_textId;
    private javax.swing.JTextField jTextField_textJumlah;
    // End of variables declaration//GEN-END:variables
}
